# Generated by Django 2.0.2 on 2018-09-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experience_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='month',
            field=models.IntegerField(default=9),
        ),
    ]
