# Generated by Django 2.0.2 on 2018-09-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180918_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='month',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='year',
        ),
    ]
