# Generated by Django 2.0.2 on 2018-09-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
    ]
