# Generated by Django 2.0.2 on 2018-09-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180917_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Información personal', 'verbose_name_plural': 'Datos personales'},
        ),
    ]
