# Generated by Django 2.0.2 on 2018-09-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20180917_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='cellphpone',
            new_name='cellphone',
        ),
    ]
