# Generated by Django 2.0.2 on 2018-09-19 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Apellido',
        ),
        migrations.AddField(
            model_name='about',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
    ]
