# Generated by Django 2.0.2 on 2018-09-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20180919_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
